# Generated by Django 2.1.3 on 2018-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181117_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='NA'),
        ),
    ]
