# Generated by Django 2.1.3 on 2018-11-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181117_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
